apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: decision-lab
spec:
  type: ClusterIP
  selector:
    app: django
    version: green   # ðŸ‘ˆ ACTIF
  ports:
    - port: 80
      targetPort: 8000
metadata:
  name: django-blue
spec:
  template:
    metadata:
      labels:
        app: django
        version: blue
metadata:
  name: django-green
spec:
  template:
    metadata:
      labels:
        app: django
        version: green
kubectl patch service django \
  -n decision-lab \
  -p '{"spec":{"selector":{"app":"django","version":"green"}}}'
