apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: decision-lab
spec:
  type: ClusterIP
  selector:
    app: django
    version: blue   # valeur par d√©faut
  ports:
    - port: 80
      targetPort: 8000
