apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: decision-lab
data:
  DJANGO_SETTINGS_MODULE: config.settings.prod
  DJANGO_DEBUG: "false"
  DJANGO_ALLOWED_HOSTS: "api.decision-lab.com"

  # Django
  DJANGO_TIME_ZONE: Europe/Paris
  LOG_LEVEL: INFO

  # Redis / Celery (NON sensible)
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  CELERY_BROKER_URL: redis://redis:6379/0
