apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django
  namespace: decision-lab
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "5"
    nginx.ingress.kubernetes.io/limit-conn: "20"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.rustcomparator.com
      secretName: decision-lab-tls
  rules:
    - host: api.rustcomparator.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: django
                port:
                  number: 80
